apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: promtail
    releaseName: promtail
    namespace: guardian
    repo: https://grafana.github.io/helm-charts
    version: x.x.x
    valuesInline:
      defaultVolumeMounts:
        - name: pods
          mountPath: /var/log/pods
          readOnly: true
        - name: run
          mountPath: /run/promtail
      defaultVolumes:
        - name: pods
          hostPath:
            path: /var/log/pods
        - name: run
          emptyDir: { }
#  - name: loki
#    releaseName: loki
#    namespace: guardian
#    repo: https://grafana.github.io/helm-charts
#    version: x.x.x
#    valuesFile: values.yaml