apiVersion: v1
kind: Service
metadata:
  name: ipfs-internal
  labels:
    app: ipfs
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
      #      cloud.google.com/l4-rbs: "enabled"
    networking.gke.io/internal-load-balancer-subnet: "prod-loadbalancer"
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
spec:
  type: LoadBalancer
  selector:
    app: ipfs
  ports:
    - port: 5001
      targetPort: api
      protocol: TCP
      name: api
    - port: 8080
      targetPort: gateway
      name: gateway