apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: clickhouse
    releaseName: clickhouse
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml
    version: 4.x.x
