kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: novu-mongodb
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-13.15.3
    app.kubernetes.io/instance: novu
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "20Gi"
  storageClassName: alicloud-disk-essd