apiVersion: v1
kind: Secret
metadata:
  name: novu-mongodb
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-13.15.3
    app.kubernetes.io/instance: novu
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
  annotations:
    avp.kubernetes.io/path: "kv/data/guardian/novu"
type: Opaque
stringData:
  mongodb-root-password: "<mongodb-root-password>"
  mongodb-passwords: "<mongodb-passwords>"