apiVersion: v1
kind: ServiceAccount
metadata:
  name: novu-mongodb
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-13.15.3
    app.kubernetes.io/instance: novu
    app.kubernetes.io/managed-by: Helm
secrets:
  - name: novu-mongodb
automountServiceAccountToken: true