apiVersion: v1
kind: Secret
metadata:
  name: novu-url-mongodb
  labels:
    app.kubernetes.io/name: novu
    helm.sh/chart: novu-0.1.6
    app.kubernetes.io/instance: novu
    app.kubernetes.io/managed-by: Helm
  annotations:
    avp.kubernetes.io/path: "kv/data/guardian/novu"
type: Opaque
stringData:
  mongoUrl: "mongodb://novu_user:<mongodb-passwords>@novu-mongodb:27017/novu_db"