apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - route.yaml
#  - secrets.yaml

helmCharts:
  - name: rabbitmq
    releaseName: rabbitmq
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml
    version: 11.x.x