apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []

helmCharts:
  - name: cloudnative-pg
    releaseName: cloudnative-pg
    namespace: guardian
    repo: https://cloudnative-pg.github.io/charts
    includeCRDs: true