apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: traefik-mesh
    releaseName: traefik-mesh
    repo: https://helm.traefik.io/traefik
    valuesFile: values.yaml
    version: 4.x.x