metrics:
  deploy: false
tracing:
  deploy: false
  jaeger:
    enabled: true
    localAgentHostPort: "jaeger-agent.guardian:6831"
    samplingServerURL: "http://jaeger-agent.guardian:5778/sampling"
proxy:
  resources:
    limit:
      mem: 128Mi
      cpu: 200m
    request:
      mem: 64Mi
      cpu: 50m
  additionalArguments:
    - "--accesslog=true"
    - "--accesslog.bufferingsize=100"
    - "--accesslog.format=json"
    - "--entryPoints.web.forwardedHeaders.insecure"  # for X-Forward-For
    - "--metrics.prometheus.buckets=0.001,0.002,0.005,0.01,0.1,0.3,0.5,1.2,5.0,10.0,15.0,25.0,35.0,50.0"
controller:
  resources:
    limit:
      mem: 128Mi
      cpu: 100m
    request:
      mem: 64Mi
      cpu: 50m
