metrics:
  deploy: false
tracing:
  deploy: false
  jaeger:
    enabled: false
proxy:
  resources:
    limit:
      mem: 500Mi
      cpu: 600m
    request:
      mem: 100Mi
      cpu: 200m
  additionalArguments:
    - "--accesslog=true"
    - "--accesslog.bufferingsize=100"
    - "--accesslog.format=json"
    - "--entryPoints.web.forwardedHeaders.insecure"  # for X-Forward-For
    - "--metrics.prometheus.buckets=0.001,0.002,0.005,0.01,0.1,0.3,0.5,1.2,5.0,10.0,15.0"
controller:
  resources:
    limit:
      mem: 500Mi
      cpu: 800m
    request:
      mem: 100Mi
      cpu: 300m
