apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
  namespace: default
spec:
  forwardAuth:
    address: https://traefik-auth.naturalselectionlabs.com
    authResponseHeaders:
      - X-Forwarded-User