apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: rss3-runner
  namespace: guardian
spec:
  template:
    spec:
      labels:
        - rss3
        - rss3-network
        - rss3-io
        - linux/amd64
        - amd64
