apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [route.yaml]

helmCharts:
  - name: consul
    releaseName: consul
    namespace: guardian
    repo: https://helm.releases.hashicorp.com
    valuesFile: values.yaml
    version: x.x.x