apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: consul
  namespace: guardian
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`consul.naturalselectionlabs.com`)
      services:
        - name: consul-ui
          port: 80
      middlewares:
        - name: traefik-forward-auth
