global:
  enablePodSecurityPolicies: false
  name: consul
  datacenter: us-central1-ops
#  secretsBackend:
#    vault:
#      enabled: true
#      consulServerRole: "consul-server"
#      manageSystemACLsRole: "consul-server-acl-init"
#  enableConsulNamespaces: false
#  acls:
#    manageSystemACLs: true
#    bootstrapToken:
#      secretName: kv/consul-acl
#      secretKey: token
server:
  storage: 20Gi
  storageClass: premium-rwo
  replicas: 3
  disruptionBudget:
    # Enables registering a PodDisruptionBudget for the server
    # cluster. If enabled, it only registers the budget so long as
    # the server cluster is enabled. To disable, set to `false`.
    enabled: false
  nodeSelector: |
    cloud.google.com/compute-class: Performance
    cloud.google.com/machine-family: c3
#    cloud.google.com/pod-isolation: 50m
syncCatalog:
  enabled: true
  toConsul: true
  toK8S: false
  nodeSelector: |
    cloud.google.com/compute-class: Performance
    cloud.google.com/machine-family: c3
  #    cloud.google.com/pod-isolation: 50m
connectInject:
  enabled: false
ui:
  service:
    enabled: true

    type: LoadBalancer
    annotations: |
      cloud.google.com/neg: '{"ingress":true}'
      networking.gke.io/load-balancer-type: "Internal"
      networking.gke.io/internal-load-balancer-subnet: "prod-loadbalancer"
      networking.gke.io/internal-load-balancer-allow-global-access: "true"

