global:
  enablePodSecurityPolicies: false
  name: consul
#  datacenter: dc1
#  secretsBackend:
#    vault:
#      enabled: true
#      consulServerRole: "consul-server"
#      manageSystemACLsRole: "consul-server-acl-init"
#  enableConsulNamespaces: false
#  acls:
#    manageSystemACLs: true
#    bootstrapToken:
#      secretName: kv/consul-acl
#      secretKey: token
server:
  storage: 20Gi
  storageClass: premium-rwo
  replicas: 3
  disruptionBudget:
    # Enables registering a PodDisruptionBudget for the server
    # cluster. If enabled, it only registers the budget so long as
    # the server cluster is enabled. To disable, set to `false`.
    enabled: false
  nodeSelector: |
    cloud.google.com/compute-class: Performance
    cloud.google.com/machine-family: c3
#    cloud.google.com/pod-isolation: 50m
syncCatalog:
  enabled: true
  toConsul: true
  toK8S: false
  nodeSelector: |
    cloud.google.com/compute-class: Performance
    cloud.google.com/machine-family: c3
  #    cloud.google.com/pod-isolation: 50m
connectInject:
  enabled: false
ui:
  ingress:
    enabled: true
    ingressClassName: "traefik"

    hosts:
      - host: consul.naturalselectionlabs.com
    tls:
      - hosts:
          - consul.naturalselectionlabs.com
        secretName: consul-tls
    annotations: |
      cert-manager.io/cluster-issuer: cloudflare
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
