apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: cockroachdb
spec:
  dataStore:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "7000Gi"
        volumeMode: Filesystem
        storageClassName: alicloud-disk-essd
  resources:
    requests:
      cpu: 40000m
      memory: 70000Mi
    limits:
      cpu: 51000m
      memory: 110000Mi
  tlsEnabled: true
  image:
    name: cockroachdb/cockroach:v23.1.8
  nodes: 5
  additionalLabels:
    crdb: default
  nodeSelector:
    rss3.io/usage: crdb
  tolerations:
    - key: "rss3.io/usage"
      operator: "Equal"
      value: "crdb"
      effect: "NoSchedule"
