apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

helmCharts:
  - name: cockroachdb
    releaseName: cockroachdb
    repo: https://charts.cockroachdb.com/
    valuesFile: values.yaml
    version: 11.x.x