apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - route.yaml
  - crdbscrape.yaml

helmCharts:
  - name: cockroachdb
    releaseName: cockroachdb
    repo: https://charts.cockroachdb.com/
    valuesFile: values.yaml
    version: 11.2.3

patches:
  - patch: |-
      - op: add
        path: "/spec/dnsNames/-"
        value:
          '*.aliyun.nsl.xyz'
      - op: add
        path: "/spec/dnsNames/-"
        value:
          '*.gcp.nsl.xyz'
    target:
      kind: Certificate
      name: cockroachdb-node
  - patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/env/1"
        value:
          name: STATEFULSET_FQDN
          value: gcp.nsl.xyz
    target:
      kind: StatefulSet
      name: cockroachdb