tls:
  enabled: true
  certs:
    selfSigner:
      enabled: false
    certManager: true

storage:
  persistentVolume:
    storageClass: premium-rwo
    size: 10Ti

conf:
  cluster-name: us-central1-prod
  join:
    - roach0.aliyun.index.ai:26258
    - roach1.aliyun.index.ai:26258
    - roach2.aliyun.index.ai:26258
    - roach3.aliyun.index.ai:26258
    - roach4.aliyun.index.ai:26258
    - roach5.aliyun.index.ai:26258

statefulset:
  replicas: 6
  resources:
    requests:
      # This is intentionally low to make it work on local k3d clusters.
      cpu: 32
      memory: 128Gi
    limits:
      cpu: 32
      memory: 128Gi
  podAntiAffinity:
    # The topologyKey to be used.
    # Can be used to spread across different nodes, AZs, regions etc.
    topologyKey: kubernetes.io/hostname
  nodeSelector:
    rss3.io/usage: crdb
  tolerations:
    - key: "rss3.io/usage"
      operator: "Equal"
      value: "crdb"
      effect: "NoSchedule"