tls:
  enabled: true
  certs:
    selfSigner:
      enabled: false
    certManager: true
    certManagerIssuer:
      clientCertDuration: 672h0m0s
      clientCertExpiryWindow: 48h0m0s
      nodeCertDuration: 8760h0m0s
      nodeCertExpiryWindow: 168h0m0s


storage:
  persistentVolume:
    storageClass: premium-rwo
    size: 10Ti

conf:
#  cluster-name: us-central1-prod
  locality: region=us-central1
  join:
    - roach0.aliyun.index.ai:26258
    - roach1.aliyun.index.ai:26258
    - roach2.aliyun.index.ai:26258
    - roach3.aliyun.index.ai:26258
    - roach4.aliyun.index.ai:26258
    - roach5.aliyun.index.ai:26258

statefulset:
  replicas: 8
  resources:
    requests:
      # This is intentionally low to make it work on local k3d clusters.
      cpu: 32
      memory: 100Gi
    limits:
      cpu: 32
      memory: 100Gi
  podAntiAffinity:
    # The topologyKey to be used.
    # Can be used to spread across different nodes, AZs, regions etc.
    topologyKey: kubernetes.io/hostname
  nodeSelector:
    rss3.io/usage: crdb
  tolerations:
    - key: "rss3.io/usage"
      operator: "Equal"
      value: "crdb"
      effect: "NoSchedule"