apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []

helmCharts:
  - name: cockroachdb
    releaseName: crdb
    repo: https://charts.cockroachdb.com/
    valuesFile: values.yaml
    version: 11.x.x
    includeCRDs: true