tls:
  enabled: true
  certs:
    selfSigner:
      enabled: false
    certManager: true
    certManagerIssuer:
      clientCertDuration: 672h0m0s
      clientCertExpiryWindow: 48h0m0s
      nodeCertDuration: 8760h0m0s
      nodeCertExpiryWindow: 168h0m0s

storage:
  persistentVolume:
    storageClass: premium-rwo
service:
  public:
    type: LoadBalancer
    # Additional labels to apply to this Service.
    labels:
      app.kubernetes.io/component: cockroachdb
    # Additional annotations to apply to this Service.
    annotations:
      networking.gke.io/internal-load-balancer-allow-global-access: 'true'
      networking.gke.io/internal-load-balancer-subnet: dev-loadbalancer
      networking.gke.io/load-balancer-type: Internal
conf:
  cluster-name: us-central1-dev
  locality: provider=gcp,country=us,region=us-central1,datacenter=us-central1a
init:
  provisioning:
    enabled: true
    users:
     - name: roach
       password: <path:kv/data/guardian/cockroachdb#ADMIN_PASSWORD>
       # https://www.cockroachlabs.com/docs/stable/create-user.html#parameters
       options: [admin]

statefulset:
  resources:
    requests:
      # This is intentionally low to make it work on local k3d clusters.
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 4
      memory: 8Gi
  podAntiAffinity:
    # The topologyKey to be used.
    # Can be used to spread across different nodes, AZs, regions etc.
    topologyKey: kubernetes.io/hostname