apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guardian
resources:
  - argo-cd/prod/app.yaml
  - traefik/dev/app.yaml
  - traefik/prod/app.yaml
  - cert-manager/dev/app.yaml
  - cert-manager/prod/app.yaml