apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: loki-stack
    releaseName: loki-stack
    namespace: guardian
    repo: https://grafana.github.io/helm-charts
    version: x.x.x
    valuesFile: values.yaml
