apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows-default
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-default
  annotations:
    kubernetes.io/service-account.name: argo-workflows-default
type: kubernetes.io/service-account-token