apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- route.yaml
- secret.yaml

helmCharts:
  - name: keycloak
    valuesFile: values.yaml
    releaseName: keycloak
    version: 18.x.x
    repo: https://codecentric.github.io/helm-charts
