apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  []
  # - route.yaml
  # - secret.yaml
  # - admin.yaml

helmCharts:
  - name: keycloak
    releaseName: keycloak
    repo: https://codecentric.github.io/helm-charts
    valuesFile: values.yaml
    version: 18.x.x

patches:
  # patch ingress port from name: http to number 80
  - target:
      kind: Ingress
      name: keycloak
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/port
        value:
          number: 80
