apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml

helmCharts:
- name: keycloak
  releaseName: keycloak
  repo: https://codecentric.github.io/helm-charts
  valuesFile: values.yaml
  version: 18.x.x
