## Keycloak Configuration
keycloak:
  replicas: 3
  persistence:
    deployPostgres: false

extraEnv:   |
  - name: JAVA_OPTS
    value: >-
      -XX:+UseContainerSupport
      -XX:MaxRAMPercentage=50.0
      -Djava.net.preferIPv4Stack=true
      -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS
      -Djava.awt.headless=true
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KC_PROXY
    value: edge
  - name: KC_HOSTNAME_URL
    value: https://account.nsl.xyz
  - name: KC_METRICS_ENABLED
    value: "true"
  - name: DB_VENDOR
    value: postgres
  - name: DB_ADDR
    value: "10.147.0.8"
  - name: DB_PORT
    value: "5432"
  - name: DB_DATABASE
    value: keycloak
  - name: DB_USER_FILE
    value: /secrets/db-creds/username
  - name: DB_PASSWORD_FILE
    value: /secrets/db-creds/password
  - name: JGROUPS_DISCOVERY_PROTOCOL
    value: kubernetes.KUBE_PING
  - name: JGROUPS_DISCOVERY_PROPERTIES
    value: dump_requests=true,port_range=0,namespace=guardian

extraVolumeMounts: |
  - name: db-creds
    mountPath: /secrets/db-creds
    readOnly: true

extraVolumes: |
  - name: db-creds
    secret:
      secretName: keycloak-db-creds
## PostgreSQL Configuration
postgresql:
  enabled: false

## Resources Configuration
resources:
  limits:
    cpu: "1"
    memory: 2048Mi
  requests:
    cpu: "500m"
    memory: 1024Mi

serviceMonitor:
  enabled: true