## Keycloak Configuration
keycloak:
  persistence:
    deployPostgres: false
replicas: 3
extraEnv:   |
  - name: JAVA_OPTS
    value: >-
      -XX:+UseContainerSupport
      -XX:MaxRAMPercentage=50.0
      -Djava.net.preferIPv4Stack=true
      -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS
      -Djava.awt.headless=true
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KC_PROXY
    value: edge
  - name: KC_HOSTNAME_URL
    value: https://account.naturalselectionlabs.com
  - name: KC_METRICS_ENABLED
    value: "true"
  - name: KC_CACHE_STACK
    value: "kubernetes"
  - name: DB_VENDOR
    value: postgres
  - name: DB_ADDR
    value: "10.147.0.8"
  - name: DB_PORT
    value: "5432"
  - name: DB_DATABASE
    value: keycloak
  - name: DB_USER_FILE
    value: /secrets/db-creds/username
  - name: DB_PASSWORD_FILE
    value: /secrets/db-creds/password
  - name: JGROUPS_DISCOVERY_PROTOCOL
    value: dns.DNS_PING
  - name: JGROUPS_DISCOVERY_PROPERTIES
    value: dns_query=keycloak-headless.guardian.svc.cluster.local
  - name: KEYCLOAK_STATISTICS
    value: all

extraEnvFrom: |
  - secretRef:
      name: keycloak-admin

extraVolumeMounts: |
  - name: db-creds
    mountPath: /secrets/db-creds
    readOnly: true

extraVolumes: |
  - name: db-creds
    secret:
      secretName: keycloak-db-creds
## PostgreSQL Configuration
postgresql:
  enabled: false

## Resources Configuration
resources:
  requests:
    cpu: "1"
    memory: 2Gi

serviceMonitor:
  enabled: true


rbac:
  create: true
  rules:
  # RBAC rules for KUBE_PING
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - get
        - list

#ingress:
#  enabled: true
#  ingressClassName: "traefik"
#  # The Service port targeted by the Ingress
#  servicePort: http
#  # Ingress annotations
#  annotations:
#    cert-manager.io/cluster-issuer: "cloudflare"
#    traefik.ingress.kubernetes.io/router.entrypoints: websecure
#  rules:
#    -
#      host: 'account.naturalselectionlabs.com'
#      # Paths for the host
#      paths:
#        - path: /
#          pathType: Prefix
#  # Example TLS configuration
#      tls:
#        - hosts:
#            - keycloak.example.com
#          secretName: "keycloak-tls"
#
#  # ingress for console only (/auth/admin)
#  console:
#    # If `true`, an Ingress is created for console path only
#    enabled: true
#    # The name of Ingress Class associated with the console ingress only
#    ingressClassName: "traefik"
#    # Ingress annotations for console ingress only
#    # Useful to set nginx.ingress.kubernetes.io/whitelist-source-range particularly
#    annotations:
#      traefik.ingress.kubernetes.io/router.entrypoints: websecure
#    rules:
#      -
#        # Ingress host
#        host: 'account.naturalselectionlabs.com'
#        # Paths for the host
#        paths:
#          - path: /auth/admin/
#            pathType: Prefix
#    # Console TLS configuration
#    tls:
#      - hosts:
#          - keycloak.example.com
#        secretName: "keycloak-tls"