apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  high-availability:
    replicas: 2
  ingress:
    kourier:
      enabled: true
      service-type: "NodePort"
      http-port: 31080
      https-port: 31443
  config:
    autoscaler:
      enable-scale-to-zero: "true"
      scale-to-zero-grace-period: "40s"
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"
      autocreate-cluster-domain-claims: "true"
    certmanager:
      clusterLocalIssuerRef: |
        kind: ClusterIssuer
        name: cloudflare
      issuerRef: |
        kind: ClusterIssuer
        name: cloudflare
      systemInternalIssuerRef: |
        kind: ClusterIssuer
        name: cloudflare
