apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
spec:
  high-availability:
    replicas: 2
  config:
    autoscaler:
      enable-scale-to-zero: "true"
      scale-to-zero-grace-period: "40s"
    network:
      ingress-class: "traefik"
    certmanager:
      clusterLocalIssuerRef: |
        kind: ClusterIssuer
        name: cloudflare
      issuerRef: |
        kind: ClusterIssuer
        name: cloudflare
      systemInternalIssuerRef: |
        kind: ClusterIssuer
        name: cloudflare
