kind: Service
apiVersion: v1
metadata:
  name: logstash-loki
  namespace: guardian
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5044
      targetPort: 5044
  selector:
    app: logstash-loki
  clusterIP: None
  type: ClusterIP
