apiVersion: v1
kind: Service
metadata:
  name: loki-internal
  namespace: guardian
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-name: "loki-dev"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: "slb.s1.small"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: "intranet"
spec:
  ports:
    - name: http-metrics
      protocol: TCP
      port: 3100
      targetPort: http-metrics
  selector:
    app: loki
    release: loki
  type: ClusterIP
