loki:
  auth_enabled: false
  storage:
    type: gcs
    bucketNames:
      chunks: nsl-loki-uscentral1-dev
      ruler: nsl-loki-uscentral1-dev
      admin: nsl-loki-uscentral1-dev
    gcs:
      bucket_name: nsl-loki-uscentral1-dev
  limits_config:
    ingestion_rate_mb: 1024
    ingestion_burst_size_mb: 1024
  structuredConfig:
    storage_config:
      tsdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/index_cache
        cache_ttl: 24h
      gcs:
        bucket_name: nsl-loki-uscentral1-dev
#  config:
#    compactor:
#      retention_enabled: true
#      retention_delete_delay: 2h
#      retention_delete_worker_count: 150
#    chunk_store_config:
#      max_look_back_period: 168h
#    schema_config:
#      configs:
#        - from: 2020-05-15
#          store: boltdb
#          object_store: gcs
#          schema: v11
#          index:
#            prefix: loki_index_
#            period: 168h
#    storage_config:
#      boltdb:
#        directory: /data/loki/index
#      gcs:
#        bucket_name: nsl-loki-uscentral1-dev
#    server:
#      grpc_server_max_recv_msg_size: 104857600
#    limits_config:
#      reject_old_samples: true
#      retention_period: 168h
#      per_stream_rate_limit: "15MB"
#      per_stream_rate_limit_burst: "30MB"
#      ingestion_rate_mb: 15
#      ingestion_burst_size_mb: 30
#      max_entries_limit_per_query: 10000
#      max_global_streams_per_user: 10000
#    table_manager:
#      retention_deletes_enabled: true
#      retention_period: 168h
#    ruler:
#      storage:
#        type: gcs
#        gcs:
#          bucket_name: nsl-loki-uscentral1-dev
#      rule_path: /tmp/scratch
#      alertmanager_url: http://alertmanager.svc.namespace:9093
#      ring:
#        kvstore:
#          store: inmemory
#      enable_api: true
  commonConfig:
    replication_factor: 1
  rulerConfig:
    alertmanager_url: http://vmalertmanager-victoriametrics-0.vmalertmanager-victoriametrics.guardian.svc:9093
    enable_alertmanager_v2: true
    ring:
      kvstore:
        store: inmemory
    enable_api: true
  schemaConfig:
    configs:
      - from: 2020-07-01
        store: tsdb
        object_store: gcs
        schema: v13
        index:
          prefix: index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  tracing:
    enabled: true
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 2
serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: loki-sa@naturalselectionlabs.iam.gserviceaccount.com
deploymentMode: SingleBinary
singleBinary:
  replicas: 1
  persistence:
    enabled: false
  extraVolumes:
    - name: data
      emptyDir: { }
  extraVolumeMounts:
    - name: data
      mountPath: /var/loki
  resources:
    limits:
      cpu: 3
      memory: 4Gi
    requests:
      cpu: 2
      memory: 2Gi
  extraEnv:
    # Keep a little bit lower than memory limits
    - name: GOMEMLIMIT
      value: 3750MiB

chunksCache:
  # default is 500MB, with limited memory keep this smaller
  writebackSizeLimit: 10MB
# Zero out replica counts of other deployment modes
# Configuration for the memberlist service
memberlist:
  service:
    publishNotReadyAddresses: true
gateway:
  service:
    type: LoadBalancer
    annotations:
      networking.gke.io/load-balancer-type: "Internal"
      networking.gke.io/internal-load-balancer-subnet: "dev-loadbalancer"
      networking.gke.io/internal-load-balancer-allow-global-access: "true"
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0