loki:
  enabled: true
  podAnnotations:
    prometheus.io/port: "3100"
  persistence:
    enabled: false
  config:
    compactor:
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
    chunk_store_config:
      max_look_back_period: 168h
    schema_config:
      configs:
        - from: 2020-05-15
          store: boltdb
          object_store: gcs
          schema: v11
          index:
            prefix: loki_index_
            period: 168h
    storage_config:
      boltdb:
        directory: /data/loki/index
      gcs:
        bucket_name: nsl-loki-uscentral1-dev
    server:
      grpc_server_max_recv_msg_size: 104857600
    limits_config:
      reject_old_samples: true
      retention_period: 168h
      per_stream_rate_limit: "15MB"
      per_stream_rate_limit_burst: "30MB"
      ingestion_rate_mb: 15
      ingestion_burst_size_mb: 30
      max_entries_limit_per_query: 10000
      max_global_streams_per_user: 10000
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h
    ruler:
      storage:
        type: gcs
        gcs:
          bucket_name: nsl-loki-uscentral1-dev
      rule_path: /tmp/scratch
      alertmanager_url: http://alertmanager.svc.namespace:9093
      ring:
        kvstore:
          store: inmemory
      enable_api: true
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: loki-sa@naturalselectionlabs.iam.gserviceaccount.com
promtail:
  enabled: true

fluent-bit:
  enabled: false

grafana:
  enabled: false

prometheus:
  enabled: false
