apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: umami
  namespace: guardian
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: Host(`umami.rss3.io`)
    services:
    - name: umami
      port: 3000
