apiVersion: v1
kind: Secret
metadata:
  name: umami
  namespace: guardian
  annotations:
    avp.kubernetes.io/path: "kv/data/guardian/umami"
type: Opaque
stringData:
  hash-salt: "<hash-salt>"
  db-url: "postgresql://<postgres-username>:<postgres-password>@<postgres-hostname>:5432/umami?sslmode=disable"