provisionDataStore:
  cassandra: true

storage:
  type: cassandra
  cassandra:
    host: cassandra
    port: 9042
    user: user
    password: password
    usePassword: true
    keyspace: jaeger_v1_test

cassandra:
  persistence:
    enabled: true
    storageClass: "standard"
    size: 400Gi
  nodeSelector:
    rss3.io/usage: internal
  tolerations:
    - key: "rss3.io/usage"
      operator: "Equal"
      value: "internal"
      effect: "NoSchedule"

agent:
  enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 256m
      memory: 128Mi

collector:
  enabled: true
  replicaCount: 3
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 7
  service:
    type: ClusterIP
    grpc:
      port: 14250
    http:
      port: 14268
    otlp:
      grpc:
        name: otlp-grpc
        port: 4317
      http:
        name: otlp-http
        port: 4318
  resources:
    limits:
      cpu: "2"
      memory: 1Gi
    requests:
      cpu: "1"
      memory: 256Mi
  nodeSelector:
    rss3.io/usage: internal
  tolerations:
    - key: "rss3.io/usage"
      operator: "Equal"
      value: "internal"
      effect: "NoSchedule"

query:
  enabled: true
  agentSidecar:
    enabled: false
  replicaCount: 1
  resources:
    limits:
      cpu: 600m
      memory: 2048Mi
    requests:
       cpu: 256m
       memory: 128Mi
  nodeSelector:
    rss3.io/usage: internal
  tolerations:
    - key: "rss3.io/usage"
      operator: "Equal"
      value: "internal"
      effect: "NoSchedule"
