apiVersion: apps/v1
kind: Deployment
metadata:
  name: novu-ws
  labels:
    app.kubernetes.io/name: novu
    helm.sh/chart: novu-0.1.6
    app.kubernetes.io/instance: novu
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: novu-ws
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: novu
      app.kubernetes.io/instance: novu
      app.kubernetes.io/component: novu-ws
  template:
    metadata:
      labels:
        app.kubernetes.io/name: novu
        helm.sh/chart: novu-0.1.6
        app.kubernetes.io/instance: novu
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: novu-ws
    spec:
      serviceAccountName: novu
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: novu
                    app.kubernetes.io/instance: novu
                    app.kubernetes.io/component: novu-ws
                topologyKey: kubernetes.io/hostname
              weight: 1
      containers:
        - name: novu-ws
          image: ghcr.io/novuhq/novu/ws:0.15.0
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value : "production"
            - name: PORT
              value : "3002"
            - name: MONGO_MIN_POOL_SIZE
              value : "10"
            - name: MONGO_MAX_POOL_SIZE
              value : "50"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: novu-externalredis
                  key: redis-host
            - name: REDIS_PORT
              value : "6379"
            - name: REDIS_PASSWORD
              valueFrom :
                secretKeyRef:
                  name: novu-externalredis
                  key: redis-password
            - name: MONGO_URL
              valueFrom :
                secretKeyRef:
                  name: novu-url-mongodb
                  key: mongoUrl
            - name: JWT_SECRET
              valueFrom :
                secretKeyRef:
                  name: novu
                  key: jwt-secret
          ports:
            - name: http
              containerPort: 3002
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: /v1/health-check
              port: http
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: /v1/health-check
              port: http
