apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []

helmCharts:
  - name: pyroscope
    releaseName: pyroscope
    repo: https://grafana.github.io/helm-charts
    version: x.x.x
    valuesFile: values.yaml