apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pyroscope
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pyroscope.dev.naturalselectionlabs.com`)
      kind: Rule
      services:
        - name: pyroscope
          port: 4040