apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: discourse
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: discourse
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 150
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 100