apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - route.yaml
  - secret.yaml

helmCharts:
  - name: discourse
    releaseName: discourse
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml
    version: 12.x.x