apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: discourse
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`forum.rss3.io`)
      services:
        - name: discourse
          port: 80