apiVersion: v1
kind: Secret
metadata:
  name: discourse
  annotations:
    avp.kubernetes.io/path: "kv/data/default/discourse"
type: Opaque
stringData:
  postgres-password: "<POSTGRES_PASSWORD>"
  redis-password: "<REDIS_PASSWORD>"
  discourse-password: "<DISCOURSE_PASSWORD>"
  smtp-password: "<SMTP_PASSWORD>"

