apiVersion: v1
kind: Secret
metadata:
  name: discourse
  annotations:
    avp.kubernetes.io/path: "kv/data/default/discourse"
type: Opaque
stringData:
  postgres_password: "<POSTGRES_PASSWORD>"
  redis_password: "<REDIS_PASSWORD>"
  discourse-password: "<DISCOURSE_PASSWORD>"

