discourse:
#  skipInstall: true
  plugins:
    - https://github.com/discourse/discourse-openid-connect
  extraEnvVars:
    - name: SKIP_POST_DEPLOYMENT_MIGRATIONS
      value: "true"
  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 2
      memory: 4Gi
replicaCount: 3
postgresql:
  enabled: false
redis:
  enabled: false
persistence:
  storageClass: "standard-rwm"
  accessModes:
    - ReadWriteMany
host: forum.rss3.io
auth:
  email: forum@rss3.io
  username: admin
  existingSecret: "discourse"
smtp:
  enabled: true
  host: "smtp.gmail.com"
  port: "587"
  user: "forum@rss3.io"
  protocol: "tls"
  auth: "plain"
  existingSecret: "discourse"
externalDatabase:
  host: 10.147.0.8
  user: postgres
  database: discourse
  create: false
  existingSecret: "discourse"
  existingSecretPasswordKey: "postgres-password"
  existingSecretPostgresPasswordKey: "postgres-password"
externalRedis:
  host: 10.147.1.11
  port: 6379
  existingSecret: "discourse"
  existingSecretPasswordKey: "redis-password"