postgresql:
  enabled: false
redis:
  enabled: false
persistence:
  storageClass: "standard-rwm"
  accessModes:
    - ReadWriteMany
host: forum.rss3.io
auth:
  email: contact@rss3.io
  username: admin
  existingSecret: "discourse"
externalDatabase:
  host: 10.147.0.8
  user: postgres
  database: discourse
  create: false
  existingSecret: "discourse"
  existingSecretPasswordKey: "postgres-password"
  existingSecretPostgresPasswordKey: "postgres-password"
externalRedis:
  host: 10.147.1.11
  port: 6379
  existingSecret: "discourse"
  existingSecretPasswordKey: "redis-password"