apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - httpbin.yaml
  - cert.yaml
  - ../base

helmCharts:
  - name: traefik
    releaseName: traefik
    namespace: guardian
    repo: https://helm.traefik.io/traefik
    valuesFile: values.yaml
    version: 27.x.x
    includeCRDs: true
