apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: consul
  namespace: guardian
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`consul.dev.nsl.xyz`)
      services:
        - name: consul-ui
          port: 80
