apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []

helmCharts:
  - name: argocd-image-updater
    releaseName: argocd-image-updater
    repo: https://argoproj.github.io/argo-helm
    version: 0.x.x
    valuesFile: values.yaml
    apiVersions:
      - monitoring.coreos.com/v1
