agent: false
operator:
  enabled: false
cni:
  install: false
hubble:
  enabled: false
  relay:
    # set this to false as Hubble relay is already installed
    enabled: false
    tls:
      server:
        # set this to true if tls is enabled on Hubble relay server side
        enabled: true
  ui:
    # enable Hubble UI
    enabled: true
    standalone:
      # enable Hubble UI standalone deployment
      enabled: true
      # provide a volume containing Hubble relay client certificates to mount in Hubble UI pod
      tls:
        certsVolume:
          projected:
            defaultMode: 0400
            sources:
              - secret:
                  name: hubble-relay-client-certs
                  items:
                    - key: tls.crt
                      path: client.crt
                    - key: tls.key
                      path: client.key
                    - key: ca.crt
                      path: hubble-relay-ca.crt