apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml

helmCharts:
  - name: etcd
    releaseName: etcd
    repo: oci://registry-1.docker.io/bitnamicharts
    valuesFile: values.yaml
    version: 10.x.x
    namespace: guardian