apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml

helmCharts:
  - name: etcd
    releaseName: etcd
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml
    version: x.x.x
    namespace: guardian