replicaCount: 1
persistence:
  storageClass: standard
  size: 100Gi
auth:
  token:
    type: simple
  rbac:
    existingSecret: etcd
podAnnotations:
  prometheus.io/path: /metrics
  prometheus.io/port: '2379'
  prometheus.io/scrape: 'true'