apiVersion: monitoring.grafana.com/v1alpha1
kind: Integration
metadata:
  name: gcp-exporter
  labels:
    agent: grafana-agent
spec:
  name: gcp
  type:
    allNodes: false
    unique: true
  config:
    autoscrape:
      enable: true
      metrics_instance: grafana/grafana-agent-metrics
    project_ids:
      - naturalselectionlabs
      - rss3-409706
      - crossbell-409411
    gcp_client_timeout: 15s
    metrics_prefixes:
      - compute.googleapis.com/
      - storage.googleapis.com/
      - redis.googleapis.com/
      - cloudsql.googleapis.com/
      - networking.googleapis.com/
      - loadbalancing.googleapis.com/
      - autoscaler.googleapis.com/
