apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true


resources:
  - route.yaml

configMapGenerator:
  - name: grafana-agent
    files:
      - config.river

helmCharts:
  - name: grafana-agent
    releaseName: grafana-agent
    repo: https://grafana.github.io/helm-charts
    version: x.x.x
    valuesFile: values.yaml