apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: grafana-agent
    releaseName: grafana-agent
    repo: https://grafana.github.io/helm-charts
    version: x.x.x
    valuesFile: values.yaml