serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: grafana-agent@naturalselectionlabs.iam.gserviceaccount.com
agent:
  clustering:
    enabled: true
  configMap:
    create: false
    name: grafana-agent
    key: config.river

controller:
  type: 'deployment'
  replicas: 3