apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml

helmCharts:
  - name: actions-runner-controller
    releaseName: actions-runner-controller
    repo: https://actions-runner-controller.github.io/actions-runner-controller
    valuesFile: values.yaml
    version: 0.x.x