apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - route.yaml

helmCharts:
  - name: jaeger
    releaseName: jaeger
    repo: https://jaegertracing.github.io/helm-charts
    valuesFile: values.yaml
    version: 0.71.x