apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme
  namespace: guardian
spec:
  acme:
    email: areswang@rss3.io
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: acme-cert-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cf-nsl-xyz-api-token
              key: api-token