apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
  namespace: guardian
spec:
  acme:
    email: devops@rss3.io
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: cloudflare-cert-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cf-api-token
              key: api-token