apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterissuer.yaml

helmCharts:
  - name: cert-manager
    releaseName: cert-manager
    repo: https://charts.jetstack.io
    valuesFile: values.yaml
    version: 1.11.x
    namespace: guardian