apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-pub
  namespace: guardian
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`dashboard.rss3.dev`)
    services:
    - name: grafana-pub
      port: 80
    middlewares:
      - name: grafana-pub-add-x-webauth-user
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: grafana-pub-add-x-webauth-user
  namespace: guardian
spec:
  headers:
    customRequestHeaders:
      X-WEBAUTH-USER: "viewer"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-pub-admin
  namespace: guardian
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`grafana-pub.kindjeff.com`)
    services:
    - name: grafana-pub
      port: 80
    middlewares:
      - name: rm-x-webauth-user
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rm-x-webauth-user
  namespace: guardian
spec:
  headers:
    customRequestHeaders:
      X-WEBAUTH-USER: ""
