apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alert-svc.yaml
  - secret.yaml
  - route.yaml

helmCharts:
  - name: grafana
    releaseName: grafana
    repo: https://grafana.github.io/helm-charts
    valuesFile: values.yaml
    version: 6.57.4