resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 512Mi
replicas: 3
nodeSelector:
  rss3.io/usage: internal
tolerations:
  - key: "rss3.io/usage"
    operator: "Equal"
    value: "internal"
    effect: "NoSchedule"
admin:
  existingSecret: "grafana-secrets"
  userKey: admin-user
  passwordKey: admin-password
namespaceOverride: "guardian"
envFromSecrets:
  - name: grafana-ext-config
grafana.ini:
  server:
    domain: grafana.nsl.xyz
    root_url: "https://%(domain)s"
    serve_from_sub_path: false
  database:
    type: postgres
    host: pgm-7go76ijtdor158l6195200.pg.rds.aliyuncs.com
    user: grafana
    name: grafana
  auth.generic_oauth:
    enabled: true
    name: Natural Selection Labs
    allow_sign_up: true
    scopes: openid email profile offline_access roles
    email_attribute_path: email
    login_attribute_path: username
    name_attribute_path: full_name
    auth_url: https://account.nsl.xyz/auth/realms/google/protocol/openid-connect/auth
    token_url: https://account.nsl.xyz/auth/realms/google/protocol/openid-connect/token
    api_url: https://account.nsl.xyz/auth/realms/google/protocol/openid-connect/userinfo
    signout_redirect_url: https://account.nsl.xyz/auth/realms/google/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2grafana.nsl.xyz%2Flogin
    role_attribute_path: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'
  unified_alerting:
    enabled: true
    ha_listen_address: "${POD_IP}:9094"
    ha_peers: "grafana-alerting.guardian:9094"
    ha_advertise_address: "${POD_IP}:9094"
    ha_peer_timeout: 15s
  # auth.google:
  #   enabled: true
  #   auto_login: false
  #   auth_url: https://accounts.google.com/o/oauth2/auth
  #   scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
  #   token_url: https://accounts.google.com/o/oauth2/token
enableServiceLinks: false
