resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 1
    memory: 1Gi
replicas: 3
ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: "cloudflare"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - grafana.naturalselectionlabs.com
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.naturalselectionlabs.com
admin:
  existingSecret: "grafana-secrets"
  userKey: admin-user
  passwordKey: admin-password
namespaceOverride: "guardian"
envFromSecrets:
  - name: grafana-ext-config
grafana.ini:
  server:
    domain: grafana.naturalselectionlabs.com
    root_url: "https://%(domain)s"
    serve_from_sub_path: false
  database:
    type: postgres
    host: 10.147.0.8
    user: postgres
    name: grafana
  auth:
    oauth_allow_insecure_email_lookup: true
  auth.generic_oauth:
    enabled: true
    name: Natural Selection Labs
    allow_sign_up: true
    scopes: openid email profile offline_access roles
    email_attribute_path: email
    login_attribute_path: username
    name_attribute_path: full_name
    auth_url: https://account.naturalselectionlabs.com/auth/realms/google/protocol/openid-connect/auth
    token_url: https://account.naturalselectionlabs.com/auth/realms/google/protocol/openid-connect/token
    api_url: https://account.naturalselectionlabs.com/auth/realms/google/protocol/openid-connect/userinfo
    signout_redirect_url: https://account.naturalselectionlabs.com/auth/realms/google/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2grafana.naturalselectionlabs.com%2Flogin
    role_attribute_path: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'
  unified_alerting:
    enabled: true
    ha_listen_address: "${POD_IP}:9094"
    ha_peers: "grafana-alerting.guardian:9094"
    ha_advertise_address: "${POD_IP}:9094"
    ha_peer_timeout: 15s
  # auth.google:
  #   enabled: true
  #   auto_login: false
  #   auth_url: https://accounts.google.com/o/oauth2/auth
  #   scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
  #   token_url: https://accounts.google.com/o/oauth2/token
enableServiceLinks: false
