apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

helmCharts:
  - name: promtail
    releaseName: promtail
    repo: https://grafana.github.io/helm-charts
    version: 6.15.x
    valuesInline:
      serviceMonitor:
        enabled: true
      tolerations:
        - operator: Exists
          effect: NoSchedule
  - name: loki
    releaseName: loki
    repo: https://grafana.github.io/helm-charts
    version: x.x.x
    valuesFile: values.yaml