loki:
  auth_enabled: false
  storage:
    type: gcs
    bucketNames:
      chunks: nsl-loki-uscentral1-prod
      ruler: nsl-loki-uscentral1-prod
      admin: nsl-loki-uscentral1-prod
    gcs:
      bucket_name: nsl-loki-uscentral1-prod
  server:
    grpc_server_max_recv_msg_size: 16777216
    grpc_server_max_send_msg_size: 16777216
  limits_config:
    ingestion_rate_mb: 1024
    ingestion_burst_size_mb: 1024
    max_concurrent_tail_requests: 100
    max_line_size: 10MB
  structuredConfig:
    storage_config:
      tsdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/index_cache
        cache_ttl: 24h
      gcs:
        bucket_name: nsl-loki-uscentral1-prod
  commonConfig:
    replication_factor: 1
  rulerConfig:
    alertmanager_url: http://vmalertmanager-victoriametrics.guardian.svc:9093
    enable_alertmanager_v2: true
    ring:
      kvstore:
        store: memberlist
    enable_api: true
  schemaConfig:
    configs:
      - from: 2020-07-01
        store: tsdb
        object_store: gcs
        schema: v13
        index:
          prefix: index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  tracing:
    enabled: true
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 4
serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: loki-sa@naturalselectionlabs.iam.gserviceaccount.com
deploymentMode: SingleBinary
singleBinary:
  replicas: 3
  persistence:
    enabled: false
  extraVolumes:
    - name: data
      emptyDir: { }
  extraVolumeMounts:
    - name: data
      mountPath: /var/loki
  resources:
    limits:
      cpu: 3
      memory: 4Gi
    requests:
      cpu: 2
      memory: 2Gi
  extraEnv:
    # Keep a little bit lower than memory limits
    - name: GOMEMLIMIT
      value: 3750MiB
    - name: JAEGER_AGENT_HOST
      value: jaeger-agent.guardian.svc.cluster.local
    - name: JAEGER_AGENT_PORT
      value: "6831"
    - name: JAEGER_SAMPLER_TYPE
      value: const
    - name: JAEGER_SAMPLER_PARAM
      value: "1"

chunksCache:
  # default is 500MB, with limited memory keep this smaller
  writebackSizeLimit: 10MB
# Zero out replica counts of other deployment modes
# Configuration for the memberlist service
memberlist:
  service:
    publishNotReadyAddresses: true
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
monitoring:
  serviceMonitor:
    enabled: true