loki:
  image:
    tag: "2.9.3"
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: "cloudflare"
    hosts:
      - host: loki.ovh.naturalselectionlabs.com
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loki-stack
                port:
                  number: 3100

    tls:
      - secretName: loki-tls
        hosts:
          - loki.ovh.naturalselectionlabs.com
