tls:
  enabled: true
  certs:
    selfSigner:
      enabled: false
    certManager: true
    certManagerIssuer:
      clientCertDuration: 672h0m0s
      clientCertExpiryWindow: 48h0m0s
      nodeCertDuration: 8760h0m0s
      nodeCertExpiryWindow: 168h0m0s


storage:
  persistentVolume:
    storageClass: premium-rwo
    size: 100Gi

conf:
  cluster-name: crossbell-prod
  locality: region=us-central1

statefulset:
  replicas: 3
  resources:
    requests:
      # This is intentionally low to make it work on local k3d clusters.
      cpu: 8
      memory: 8Gi
    limits:
      cpu: 8
      memory: 8Gi
  podAntiAffinity:
    # The topologyKey to be used.
    # Can be used to spread across different nodes, AZs, regions etc.
    topologyKey: kubernetes.io/hostname

init:
  provisioning:
    enabled: true