apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: rss3-runner
  namespace: guardian
spec:
  replicas: 2
  template:
    spec:
      githubAPICredentialsFrom:
        secretRef:
          name: action-runner-controller-rss3
      dockerdWithinRunnerContainer: true
      group: Default
      automountServiceAccountToken: true
      envFrom:
        - secretRef:
            name: rss3-runner
      labels:
        - rss3
        - rss3-network
        - rss3-io
      image: summerwind/actions-runner-dind
      organization: RSS3-Network
      resources:
        requests:
          cpu: '4'
          memory: 8Gi
