apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: shlink
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`shlink.rss3.io`)
      services:
      - name: shlink
        port: 80
