apiVersion: v1
kind: Secret
metadata:
  name: shlink
  annotations:
    avp.kubernetes.io/path: "kv/data/default/shlink"
type: Opaque
stringData:
  DEFAULT_DOMAIN: "shlink.rss3.io"
  IS_HTTPS_ENABLED: "false"
  DB_DRIVER: "postgres"
  DB_NAME: "shlink"
  DB_USER: "postgres"
  DB_HOST: "<DB_HOST>"
  DB_PORT: "5432"
  DB_PASSWORD: "<DB_PASSWORD>"
  REDIS_SERVERS: "<REDIS_SERVERS>"
