apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../forward-auth

helmCharts:
  - name: traefik
    releaseName: traefik
    repo: https://helm.traefik.io/traefik
    valuesFile: values.yaml
    version: x.x.x
    includeCRDs: true