apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - secret.yaml

helmCharts:
  - name: argo-workflows
    releaseName: argo-workflows
    repo: https://argoproj.github.io/argo-helm
    includeCRDs: true
    version: x.x.x
    namespace: guardian
    valuesFile: values.yaml