apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - httpbin.yaml
  - servicemonitor.yaml
  - ../forward-auth

helmCharts:
  - name: traefik
    releaseName: traefik
    repo: https://helm.traefik.io/traefik
    valuesFile: values.yaml
    version: 26.x.x
    includeCRDs: true
