apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik
spec:
  jobLabel: traefik
  endpoints:
    - targetPort: metrics
      path: /metrics
      relabelings:
        - sourceLabels:
          - service
          regex: ^([^-]+)-.*$
          replacement: ${1}
          targetLabel: target_namespace
        - sourceLabels:
          - service
          regex: "^[^-]+-(.*)-[^@]+@.*$"
          replacement: ${1}
          targetLabel: target_service
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: traefik
