service:
  enabled: true
  type: LoadBalancer
  annotations:
    cloud.google.com/l4-rbs: "enabled"
    networking.gke.io/internal-load-balancer-subnet: "dev-loadbalancer"
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
deployment:
  kind: Deployment
  replicas: 3
ports:
  web:
    hostPort: "8000"  # for HTTP
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.dev.naturalselectionlabs.com`)
    entryPoints: ["websecure"]
    middlewares:
      - name: traefik-forward-auth
logs:
  access:
    enabled: true
    bufferingsize: "100"
    format: "json"
additionalArguments:
  - "--entryPoints.websecure.forwardedHeaders.insecure"
  - "--entryPoints.web.forwardedHeaders.insecure"
  - "--providers.kubernetescrd.allowexternalnameservices=true"
  - "--metrics.prometheus.addEntryPointsLabels=false" # web,metrics,etc
instanceLabelOverride: traefik

providers:
  kubernetesIngress:
    publishedService:
      enabled: true

metrics:
  prometheus:
    service:
      enabled: true