service:
  enabled: false
deployment:
  kind: DaemonSet
ports:
  web:
    hostPort: "8000"  # for HTTP
logs:
  access:
    enabled: true
    bufferingsize: "100"
    format: "json"
additionalArguments:
  - "--entryPoints.web.forwardedHeaders.insecure"
