service:
  enabled: false
deployment:
  kind: DaemonSet
ports:
  traefik:
    hostPort: "9000"  # for ALB health check
  web:
    hostPort: "8000"  # for HTTP
logs:
  access:
    enabled: true
additionalArguments:
  - "--entryPoints.web.forwardedHeaders.insecure"
