service:
  enabled: true
  type: LoadBalancer
  annotations:
    cloud.google.com/l4-rbs: "enabled"
    networking.gke.io/internal-load-balancer-subnet: "dev-loadbalancer"
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
deployment:
  kind: Deployment
  replicas: 3
ports:
  web:
    hostPort: "8000"  # for HTTP
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.dev.naturalselectionlabs.com`)
    entryPoints: ["websecure"]
    middlewares:
      - name: traefik-forward-auth
logs:
  access:
    enabled: true
    bufferingsize: "100"
    format: "json"
additionalArguments:
  - "--entryPoints.websecure.forwardedHeaders.insecure"
  - "--entryPoints.web.forwardedHeaders.insecure"
instanceLabelOverride: traefik

providers:
  kubernetesIngress:
    publishedService:
      enabled: true
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    buckets: "0.005,0.01,0.1,0.5,2.0,5.0,15.0,60.0"
    service:
      enabled: true
    disableAPICheck: true
    serviceMonitor:
      jobLabel: traefik
      interval: 30s
      honorLabels: true
#  openTelemetry:
#    address: jaeger-collector:4318
tracing:
  jaeger:
    samplingServerURL: http://jaeger-agent.guardian:5778/sampling
    localAgentHostPort: jaeger-agent.guardian:6831
    disableAttemptReconnecting: false