apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 8.3.2
  count: 1
  config:
    server.publicBaseUrl: "https://es.prod.nsl.xyz"
  elasticsearchRef:
    name: "elasticsearch"
  http:
    service:
      spec:
        type: LoadBalancer
        ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 5601
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    metadata:
      labels:
        k8s-app: kibana
    spec:
      nodeSelector:
        rss3.io/usage: internal
      tolerations:
      - key: "rss3.io/usage"
        operator: "Equal"
        value: "internal"
        effect: "NoSchedule"
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
            cpu: 1
