apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []

helmCharts:
  - name: mongodb
    releaseName: mongodb
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml
    version: x.x.x