apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  annotations:
    avp.kubernetes.io/path: "kv/data/guardian/mongodb"
type: Opaque
stringData:
  mongodb-root-password: "<mongodb-root-password>"
  mongodb-passwords: "<mongodb-passwords>"