apiVersion: v1
kind: Service
metadata:
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
    networking.gke.io/internal-load-balancer-subnet: "prod-loadbalancer"
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
  name: mongodb
  namespace: guardian
spec:
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodb
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: mongodb
  type: LoadBalancer

