service:
  enabled: false
deployment:
  kind: DaemonSet
ports:
  web:
    hostPort: "8000"  # for HTTP
logs:
  access:
    enabled: true
    bufferingsize: "100"
    format: "json"
additionalArguments:
  - "--entryPoints.web.forwardedHeaders.insecure"  # for X-Forward-For
  - "--metrics.prometheus.buckets=0.005,0.01,0.1,0.5,2.0,5.0,15.0,60.0"
  - "--providers.kubernetescrd.allowexternalnameservices=true"
  - "--tracing.jaeger=true"
  - "--tracing.jaeger.samplingServerURL=http://jaeger-agent.guardian:5778/sampling"
  - "--tracing.jaeger.localAgentHostPort=jaeger-agent.guardian:6831"
  - "--tracing.jaeger.disableAttemptReconnecting=false"
  - "--metrics.prometheus.addEntryPointsLabels=false" # web,metrics,etc
resources:
  requests:
    cpu: "300m"
    memory: "150Mi"
  limits:
    cpu: "800m"
    memory: "600Mi"
instanceLabelOverride: traefik
