service:
  enabled: true
  type: LoadBalancer
  annotations:
#    networking.gke.io/load-balancer-type: "Internal"
    cloud.google.com/l4-rbs: "enabled"
    networking.gke.io/internal-load-balancer-subnet: "prod-loadbalancer"
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
deployment:
  kind: Deployment
  replicas: 5
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.prod.naturalselectionlabs.com`)
    entryPoints: ["websecure"]
    middlewares:
      - name: traefik-forward-auth
logs:
  access:
    enabled: true
    bufferingsize: "100"
    format: "json"
additionalArguments:
  - "--entryPoints.web.forwardedHeaders.insecure"  # for X-Forward-For
  - "--entryPoints.websecure.forwardedHeaders.insecure"
resources:
  requests:
    cpu: "0.5"
    memory: "1Gi"
  limits:
    cpu: "0.5"
    memory: "1Gi"
instanceLabelOverride: traefik

autoscaling:
  # -- Create HorizontalPodAutoscaler object.
  enabled: true
  minReplicas: 5
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
#  - type: Resource
#    resource:
#      name: memory
#      target:
#        type: Utilization
#        averageUtilization: 60
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: '{{ template "traefik.name" . }}'
        topologyKey: kubernetes.io/hostname
tolerations:
  - key: "kubernetes.io/arch"
    operator: "Equal"
    value: "arm64"
    effect: "NoSchedule"

providers:
  kubernetesIngress:
    publishedService:
      enabled: true
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    buckets: "0.005,0.01,0.1,0.5,2.0,5.0,15.0,60.0"
    service:
      enabled: true
    disableAPICheck: true
    serviceMonitor:
      jobLabel: traefik
      interval: 30s
      honorLabels: true
      metricRelabelings:
        - sourceLabels:
            - service
          regex: ^([^-]+)-.+-.*$
          replacement: ${1}
          targetLabel: target_namespace
        - sourceLabels:
            - service
          regex: ^[^-]+-(.*)-[^@]+@.*$
          replacement: ${1}
          targetLabel: target_service
        - sourceLabels:
            - __meta_kubernetes_pod_node_name
          separator: ;
          regex: ^(.*)$
          targetLabel: nodename
          replacement: $1
          action: replace
#  openTelemetry:
#    address: jaeger-collector:4318
tracing:
  jaeger:
    samplingServerURL: http://jaeger-agent.guardian:5778/sampling
    localAgentHostPort: jaeger-agent.guardian:6831
    disableAttemptReconnecting: false

experimental:
  plugins:
    gatewayflowcontroller:
      moduleName: "github.com/RSS3-Network/gatewayflowcontroller"
      version: "v0.0.6"
