service:
  enabled: false
deployment:
  kind: DaemonSet
ports:
  web:
    hostPort: "8000"  # for HTTP
logs:
  access:
    enabled: true
    bufferingsize: "100"
additionalArguments:
  - "--entryPoints.web.forwardedHeaders.insecure"  # for X-Forward-For
  - "--metrics.prometheus.buckets=0.001,0.01,0.1,0.3,0.5,1.2,5.0,10.0,15.0"
resources:
  requests:
    cpu: "300m"
    memory: "150Mi"
  limits:
    cpu: "800m"
    memory: "600Mi"
