service:
  enabled: true
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: internet
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-instance-charge-type: PayBySpec
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: slb.s2.small
deployment:
  kind: Deployment
  replicas: 5
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.prod.nsl.xyz`)
    entryPoints: ["websecure"]
    middlewares:
      - name: traefik-forward-auth
    tls:
      secretName: traefik-cert
logs:
  access:
    enabled: true
    bufferingsize: "100"
    format: "json"
additionalArguments:
  - "--entryPoints.web.forwardedHeaders.insecure"  # for X-Forward-For
  - "--entryPoints.websecure.forwardedHeaders.insecure"
  - "--metrics.prometheus.buckets=0.005,0.01,0.1,0.5,2.0,5.0,15.0,60.0"
  - "--providers.kubernetescrd.allowexternalnameservices=true"
  - "--tracing.jaeger=true"
  - "--tracing.jaeger.samplingServerURL=http://jaeger-agent.guardian:5778/sampling"
  - "--tracing.jaeger.localAgentHostPort=jaeger-agent.guardian:6831"
  - "--tracing.jaeger.disableAttemptReconnecting=false"
  - "--metrics.prometheus.addEntryPointsLabels=false" # web,metrics,etc
resources:
  requests:
    cpu: "100m"
    memory: "400Mi"
  limits:
    cpu: "500m"
    memory: "1000Mi"
instanceLabelOverride: traefik

autoscaling:
  # -- Create HorizontalPodAutoscaler object.
  enabled: true
  minReplicas: 5
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 200
#  - type: Resource
#    resource:
#      name: memory
#      target:
#        type: Utilization
#        averageUtilization: 60
