nodeSelector:
  rss3.io/usage: internal
tolerations:
  - key: "rss3.io/usage"
    operator: "Equal"
    value: "internal"
    effect: "NoSchedule"

authSecret:
  name: "action-runner-controller-manager"