apiVersion: v1
data:
  rabbitmq-erlang-cookie: 
  rabbitmq-password: 
kind: Secret
metadata:
  name: rabbitmq
  namespace: guardian
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: rabbitmq
    meta.helm.sh/release-namespace: guardian
type: Opaque
