apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: guardian
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    avp.kubernetes.io/path: "kv/data/guardian/rabbitmq"
type: Opaque
stringData:
  rabbitmq-erlang-cookie: "<ERLANG_COOKIE>"
  rabbitmq-password: "<PASSWORD>"
