apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [vminsert.yaml]

secretGenerator:
  - name: additional-scrape-configs
    options:
      disableNameSuffixHash: true
    files:
      - prometheus-additional.yaml

helmCharts:
  - name: victoria-metrics-k8s-stack
    releaseName: victoriametrics
    namespace: guardian
    repo: https://victoriametrics.github.io/helm-charts/
    valuesFile: values.yaml
    version: 0.x.x
    includeCRDs: true
  - name: prometheus-operator-crds
    releaseName: prometheus
    namespace: guardian
    repo: https://prometheus-community.github.io/helm-charts
    version: x.x.x