apiVersion: v1
kind: Secret
metadata:
  name: traefik-forward-auth-secrets
  labels:
    app: traefik-forward-auth
  annotations:
    avp.kubernetes.io/path: "kv/data/guardian/traefik-forward-auth"
type: Opaque
stringData:
  traefik-forward-auth-oidc-client-id: "<OIDC_CLIENT_ID>"
  traefik-forward-auth-oidc-client-secret: "<OIDC_CLIENT_SECRET>"
  traefik-forward-auth-secret: "<SECRET>"