replicaCount: 2
resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

configuration:
  structuredConfig:
    modules:
      balance:
        metrics:
          - name: raw
            path: "{ . }"
        headers:
          Content-Type: application/json
        body:
          content: |
            {"jsonrpc":"2.0","method":"eth_getBalance","params":["{{ .address }}","latest"],"id":0}
