apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml

helmCharts:
  - name: argo-workflows
    releaseName: argo-workflows
    repo: https://argoproj.github.io/argo-helm
    valuesFile: values.yaml
    includeCRDs: true
    version: x.x.x
    namespace: guardian