apiVersion: v1
kind: Secret
metadata:
  name: argo-workflow-sso
  annotations:
    avp.kubernetes.io/path: "kv/data/guardian/argo-workflow"
stringData:
  client-id: "<client-id>"
  client-secret: "<client-secret>"

  