apisix:
  replicaCount: 3
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  podAnnotations:
    prometheus.io/path: /apisix/prometheus/metrics
    prometheus.io/port: '9091'
    prometheus.io/scrape: 'true'
pluginAttrs:
  prometheus:
    export_addr:
      ip: 0.0.0.0
      port: 9091
etcd:
  replicaCount: 3
  persistence:
    storageClass: alicloud-disk-essd
    size: 100Gi
  auth:
    token:
      type: simple
gateway:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: internet
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-instance-charge-type: PayBySpec
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: slb.s1.small
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-name: apisix-prod
admin:
  credentials:
    secretName: apisix-key
    secretAdminKey: ADMIN_KEY
    secretViewerKey: VIEWER_KEY
dashboard:
  enabled: true
  config:
    authentication:
      users:
        - username: admin
          password: <path:kv/data/guardian/apisix-dashboard#ADMIN_PASSWORD>
ingress-controller:
  enabled: true
  config:
    apisix:
      serviceNamespace: guardian