apisix:
  replicaCount: 3
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  podAnnotations:
    prometheus.io/path: /apisix/prometheus/metrics
    prometheus.io/port: '9091'
    prometheus.io/scrape: 'true'
logs:
  accessLogFormatEscape: json
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 200
  targetMemoryUtilizationPercentage:
pluginAttrs:
  prometheus:
    export_addr:
      ip: 0.0.0.0
      port: 9091
etcd:
  replicaCount: 3
  persistence:
    storageClass: standard
    size: 100Gi
  auth:
    token:
      type: simple
  podAnnotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '2379'
    prometheus.io/scrape: 'true'
gateway:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: internet
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-instance-charge-type: PayBySpec
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: slb.s1.small
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-name: apisix-prod
  tls:
    enabled: true
    existingCASecret: apisix-default-cert
    certCAFilename: tls.crt
admin:
  credentials:
    admin: <path:kv/data/guardian/apisix-key#ADMIN_KEY>
    viewer: <path:kv/data/guardian/apisix-key#VIEWER_KEY>
dashboard:
  enabled: true
  config:
    authentication:
      users:
        - username: admin
          password: <path:kv/data/guardian/apisix-dashboard#ADMIN_PASSWORD>
ingress-controller:
  enabled: true
  config:
    apisix:
      serviceNamespace: guardian
      adminKey: <path:kv/data/guardian/apisix-key#ADMIN_KEY>