apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      volumes:
        - name: plugins
          emptyDir: {}
      initContainers:
        - name: init-plugins
          image: curlimages/curl
          command: ['/bin/sh', '-c']
          env:
            - name: METABASE_CLICKHOUSE_DRIVER_VERSION
              value: 1.50.7
          volumeMounts:
            - mountPath: /plugins
              name: plugins
          args:
            - |
              curl -L -o /plugins/ch.jar https://github.com/ClickHouse/metabase-clickhouse-driver/releases/download/$METABASE_CLICKHOUSE_DRIVER_VERSION/clickhouse.metabase-driver.jar
      containers:
        - name: metabase
          image: metabase/metabase:v0.50.18
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - secretRef:
                name: metabase
          env:
            - name: JAVA_OPTS
              value: >-
                -XX:+UseContainerSupport
                -XX:MaxRAMPercentage=100.0
          resources:
            requests:
              cpu: "2"
              memory: 2Gi
          volumeMounts:
            - mountPath: /plugins
              name: plugins
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 60
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
