apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metabase
  annotations:
    cert-manager.io/cluster-issuer: "cloudflare"
spec:
  ingressClassName: alb
  rules:
    - host: metabase.naturalselectionlabs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metabase
                port:
                  number: 3000
  tls:
    - hosts:
        - metabase.naturalselectionlabs.com
      secretName: metabase-tls
