apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: metabase
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`mb.prod.nsl.xyz`)
      services:
        - name: metabase
          port: 3000
