apiVersion: v1
kind: Secret
metadata:
  name: metabase
  annotations:
    avp.kubernetes.io/path: "kv/data/guardian/metabase"
stringData:
  MB_DB_DBNAME: "metabase"
  MB_DB_HOST: "<MB_DB_HOST>"
  MB_DB_PASS: "<MB_DB_PASS>"
  MB_DB_PORT: "5432"
  MB_DB_TYPE: "postgres"
  MB_DB_USER: "<MB_DB_USER>"
type: Opaque
