apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: guardian
  annotations:
    avp.kubernetes.io/path: "kv/data/guardian/grafana"
type: Opaque
stringData:
  admin-user: "<ADMIN_USERNAME>"
  admin-password: "<ADMIN_PASSWORD>"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-ext-config
  namespace: guardian
  annotations:
    avp.kubernetes.io/path: "kv/data/guardian/grafana"
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "<GF_AUTH_GENERIC_OAUTH_CLIENT_ID>"
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "<GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET>"
  GF_DATABASE_PASSWORD: "<GF_DATABASE_PASSWORD>"
type: Opaque


