apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []

helmCharts:
  - name: longhorn
    releaseName: longhorn
    namespace: longhorn-system
    repo: https://charts.longhorn.io
    valuesFile: values.yaml
    includeCRDs: true
