apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-dashboard
  namespace: guardian
spec:
  dnsNames:
    - 'traefik.open.naturalselectionlabs.com'
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare
  secretName: traefik-dashboard-cert
