apiVersion: v1
kind: Secret
metadata:
  name: novu-externals3
  labels:
    app.kubernetes.io/name: novu
    helm.sh/chart: novu-0.1.6
    app.kubernetes.io/instance: novu
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: backend
  annotations:
    avp.kubernetes.io/path: "kv/data/guardian/novu"
type: Opaque
stringData:
  endpoint: "<endpoint>"
  bucketName: "<bucketName>"
  region: "<region>"
  accessKey: "<accessKey>"
  secretKey: "<secretKey>"