apiVersion: v1
kind: Service
metadata:
  name: version-checker
  labels:
    app: version-checker
spec:
  selector:
    app: version-checker
  ports:
    - protocol: TCP
      name: web
      port: 8080
      targetPort: 8080