apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: thumbor
spec:
  routes:
    - kind: Rule
      match: Host(`thumbor.follow.is`)
      services:
        - name: thumbor
          port: 8000