kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-console
  namespace: guardian
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: kafka-console
          env:
            - name: KAFKA_BROKERS
              value: 10.1.32.52:9094,10.1.32.53:9094,10.1.32.54:9094
