kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-console
  namespace: guardian
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: kafka-console
          image: docker.redpanda.com/redpandadata/console:latest
          env:
            - name: KAFKA_BROKERS
              value: 10.1.32.35:9094,10.1.32.36:9094,10.1.32.37:9094
