apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - route.yaml

patches:
  - path: deploy.yaml

helmCharts:
  - name: kafka
    releaseName: kafka
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml
    version: 23.x.x
    namespace: guardian