global:
  storageClass: "alicloud-disk-ssd"

heapOpts: -Xmx1024m -Xms1024m
deleteTopicEnable: false
autoCreateTopicsEnable: true
maxMessageBytes: _1000012

advertisedListeners:
  - PLAINTEXT://192.168.0.243:9092

replicaCount: 3
containerPorts:
  client: 9092
  internal: 9093
  external: 9094
resources:
 limits:
   cpu: 1200m
   memory: 1500Mi
 requests:
   cpu: 100m
   memory: 1024Mi
nodeSelector: {}
tolerations: []
updateStrategy:
  type: RollingUpdate
  rollingUpdate: {}

service:
  type: LoadBalancer
  ports:
    client: 9092
    internal: 9093
    external: 9094
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: intranet
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-name: kafka
persistence:
  storageClass: "alicloud-disk-ssd"
  size: 100Gi

metrics:
  kafka:
    enabled: true

zookeeper:
  enabled: true
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: "alicloud-disk-ssd"
    accessModes:
      - ReadWriteOnce
    size: 100Gi
