global:
  storageClass: "alicloud-disk-essd"

heapOpts: -Xmx1024m -Xms1024m
numPartitions: 3
logRetentionBytes: "30000000000"
deleteTopicEnable: true
autoCreateTopicsEnable: true
maxMessageBytes: _10485760

replicaCount: 3
containerPorts:
  client: 9092
  internal: 9093
  external: 9094
resources:
 limits:
   cpu: 1200m
   memory: 1500Mi
 requests:
   cpu: 100m
   memory: 1024Mi
nodeSelector: {}
tolerations: []
updateStrategy:
  type: RollingUpdate
  rollingUpdate: {}

externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
  service:
    type: LoadBalancer
    ports:
      external: 9094
    loadBalancerIPs: []
    loadBalancerNames: []
    loadBalancerAnnotations: []
    loadBalancerSourceRanges: []
    nodePorts: []
    useHostIPs: false
    usePodIPs: false
    domain: ""
    publishNotReadyAddresses: false
    labels: {}
    annotations:
      service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: intranet
      service.beta.kubernetes.io/alibaba-cloud-loadbalancer-name: kafka-external
    extraPorts: []

persistence:
  storageClass: "alicloud-disk-essd"
  size: 100Gi

rbac:
  create: true

metrics:
  kafka:
    enabled: true

kraft:
  enabled: false

zookeeper:
  enabled: true
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: "alicloud-disk-essd"
    accessModes:
      - ReadWriteOnce
    size: 100Gi
