apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - route.yaml
  - https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/stable/manifests/install.yaml

helmCharts:
  - name: argo-cd
    releaseName: argo-cd
    repo: https://argoproj.github.io/argo-helm
    valuesFile: values.yaml
    version: x.x.x