apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - route.yaml
  - github.com/argoproj-labs/argocd-image-updater/manifests/base?ref=master
  - secret.yaml
  - serviceMonitor.yaml

images:
  - name: quay.io/argoprojlabs/argocd-image-updater
    newTag: v0.13.1

helmCharts:
  - name: argo-cd
    releaseName: argocd
    repo: https://argoproj.github.io/argo-helm
    valuesFile: values.yaml
    version: 6.7.14
    namespace: guardian