apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []

configMapGenerator:
  - name: gcp-credential
    files:
      - credential-configuration.json
    options:
      disableNameSuffixHash: true

helmCharts:
  - name: argo-cd
    releaseName: argocd
    repo: https://argoproj.github.io/argo-helm
    valuesFile: values.yaml
    version: x.x.x
    additionalValuesFiles:
      - resource.yaml
    apiVersions:
      - monitoring.coreos.com/v1
