apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - route.yaml

helmCharts:
  - name: argo-cd
    releaseName: argocd
    repo: https://argoproj.github.io/argo-helm
    valuesFile: values.yaml
    version: 7.x.x
    apiVersions:
      - monitoring.coreos.com/v1