apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []

configMapGenerator:
  - name: gcp-credential
    files:
      - credential-configuration.json

helmCharts:
  - name: argo-cd
    releaseName: argocd
    repo: https://argoproj.github.io/argo-helm
    valuesFile: values.yaml
    version: 7.x.x
    apiVersions:
      - monitoring.coreos.com/v1
