apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - route.yaml
  - github.com/argoproj-labs/argocd-image-updater/manifests/base?ref=master
  - secret.yaml
  - serviceMonitor.yaml

helmCharts:
  - name: argo-cd
    releaseName: argo-cd
    repo: https://argoproj.github.io/argo-helm
    valuesFile: values.yaml
    version: 6.x.x
    namespace: guardian