configs:
  cm:
    resource.links: |
      - url: https://grafana.naturalselectionlabs.com/d/WjNUQy94z/5-7c-general-logs?orgId=1&from=now-5m&to=now&timezone=Asia%2FShanghai&var-datasource=d755e44f-61a2-4c4f-932d-f53cda0ab31e&var-namespace={{.resource.metadata.namespace}}&var-app={{.resource.metadata.name}}&var-component=$__all&var-pod=$__all&var-container=$__all&var-query0=
        title: 5-7c General Logs
        if: resource.kind == "Deployment"
    resource.exclusions: |
      ### Network resources created by the Kubernetes control plane and excluded to reduce the number of watched events and UI clutter
      - apiGroups:
        - ''
        - discovery.k8s.io
        kinds:
        - Endpoints
        - EndpointSlice
      ### Internal Kubernetes resources excluded reduce the number of watched events
      - apiGroups:
        - coordination.k8s.io
        kinds:
        - Lease
      ### Internal Kubernetes Authz/Authn resources excluded reduce the number of watched events
      - apiGroups:
        - authentication.k8s.io
        - authorization.k8s.io
        kinds:
        - SelfSubjectReview
        - TokenReview
        - LocalSubjectAccessReview
        - SelfSubjectAccessReview
        - SelfSubjectRulesReview
        - SubjectAccessReview
      ### Intermediate Certificate Request excluded reduce the number of watched events
      - apiGroups:
        - certificates.k8s.io
        kinds:
        - CertificateSigningRequest
      - apiGroups:
        - cert-manager.io
        kinds:
        - CertificateRequest
      ### Cilium internal resources excluded reduce the number of watched events and UI Clutter
      - apiGroups:
        - cilium.io
        kinds:
        - CiliumIdentity
        - CiliumEndpoint
        - CiliumEndpointSlice
      ### Kyverno intermediate and reporting resources excluded reduce the number of watched events and improve performance
      - apiGroups:
        - kyverno.io
        - reports.kyverno.io
        - wgpolicyk8s.io
        kinds:
        - PolicyReport
        - ClusterPolicyReport
        - EphemeralReport
        - ClusterEphemeralReport
        - AdmissionReport
        - ClusterAdmissionReport
        - BackgroundScanReport
        - ClusterBackgroundScanReport
        - UpdateRequest
      ### Alibaba Cloud Config Audit Report excluded reduce the number of watched events and improve performance
      - apiGroups:
        - securityinspector.alibabacloud.com
        kinds:
        - ConfigAuditReport
        clusters:
        - "*"
      ### Knative resources excluded reduce the number of watched events and improve performance
      - apiGroups:
        - caching.internal.knative.dev
        kinds:
        - Image
        clusters:
        - "*"
      - apiGroups:
        - autoscaling.internal.knative.dev
        kinds:
        - PodAutoscaler
        clusters:
        - "*"
