apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

nameSuffix: -amd64

patches:
  - target:
      kind: RunnerDeployment
      name: actions-runner
      group: actions.summerwind.dev
    patch: |-
      - op: add
        path: /spec/template/spec/labels/0
        value: amd64
      - op: add
        path: /spec/template/spec/labels/0
        value: linux/amd64