apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - route.yaml

helmCharts:
  - name: apisix
    releaseName: apisix
    repo: https://charts.apiseven.com
    valuesFile: values.yaml
    version: 1.7.x