apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: apisix-tls
  namespace: guardian
spec:
  hosts:
    - "*.dev.nsl.ooo"
  secret:
    name: apisix-default-cert
    namespace: guardian