etcd:
  replicaCount: 1
  persistence:
    storageClass: alicloud-disk-ssd
    size: 20Gi
gateway:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: internet
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-instance-charge-type: PayBySpec
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: slb.s1.small
  tls:
    enabled: true
    existingCASecret: apisix-default-cert
    certCAFilename: tls.crt
dashboard:
  enabled: true