apisix:
  replicaCount: 3
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  podAnnotations:
    prometheus.io/path: /apisix/prometheus/metrics
    prometheus.io/port: '9091'
    prometheus.io/scrape: 'true'
pluginAttrs:
  prometheus:
    export_addr:
      ip: 0.0.0.0
      port: 9091
etcd:
  replicaCount: 1
  persistence:
    storageClass: alicloud-disk-ssd
    size: 20Gi
  auth:
    token:
      type: simple
  podAnnotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '2379'
    prometheus.io/scrape: 'true'
gateway:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: internet
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-instance-charge-type: PayBySpec
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: slb.s1.small
  tls:
    enabled: true
    existingCASecret: apisix-default-cert
    certCAFilename: tls.crt
dashboard:
  enabled: true
ingress-controller:
  enabled: true
  config:
    apisix:
      serviceNamespace: guardian