apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: blackbox
spec:
  groups:
    - name: Blackbox
      rules:
        - alert: BlackboxProbeFailed
          expr: 'probe_success == 0'
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: Blackbox probe failed
            description: "Probe failed from {{ $labels.job }} (instance {{ $labels.instance }})\n"
            dashboard: https://grafana.nsl.xyz/d/NEzutrbMk?var-instance={{ $labels.instance }}&var-job={{ $labels.job }}

        - alert: BlackboxConfigurationReloadFailure
          expr: 'blackbox_exporter_config_last_reload_successful != 1'
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: Blackbox configuration reload failure
            description: "Blackbox configuration reload failure from {{ $labels.job }} (instance {{ $labels.instance }})\n"
            dashboard: https://grafana.nsl.xyz/d/NEzutrbMk?var-instance={{ $labels.instance }}&var-job={{ $labels.job }}

        - alert: BlackboxSlowProbe
          expr: 'avg_over_time(probe_duration_seconds[1m]) > 2'
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: Blackbox slow probe
            description: "Blackbox probe took more than 2s to complete from {{ $labels.job }} (instance {{ $labels.instance }})\n"
            dashboard: https://grafana.nsl.xyz/d/NEzutrbMk?var-instance={{ $labels.instance }}&var-job={{ $labels.job }}

        - alert: BlackboxProbeHttpFailure
          expr: 'probe_http_status_code <= 199 OR probe_http_status_code >= 400'
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: Blackbox probe HTTP failure
            description: "HTTP status code is not 200-399 from {{ $labels.job }} (instance {{ $labels.instance }})\n "
            dashboard: https://grafana.nsl.xyz/d/NEzutrbMk?var-instance={{ $labels.instance }}&var-job={{ $labels.job }}

        - alert: BlackboxSslCertificateWillExpireSoon
          expr: '3 <= round((last_over_time(probe_ssl_earliest_cert_expiry[10m]) - time()) / 86400, 0.1) < 20'
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: Blackbox SSL certificate will expire soon
            description: "SSL certificate expires in less than 20 days (instance {{ $labels.instance }})\n"
            dashboard: https://grafana.nsl.xyz/d/NEzutrbMk?var-instance={{ $labels.instance }}&var-job={{ $labels.job }}

        - alert: BlackboxSslCertificateWillExpireSoon
          expr: '0 <= round((last_over_time(probe_ssl_earliest_cert_expiry[10m]) - time()) / 86400, 0.1) < 3'
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: Blackbox SSL certificate will expire soon
            description: "SSL certificate expires in less than 3 days (instance {{ $labels.instance }})\n"
            dashboard: https://grafana.nsl.xyz/d/NEzutrbMk?var-instance={{ $labels.instance }}&var-job={{ $labels.job }}

        - alert: BlackboxSslCertificateExpired
          expr: 'round((last_over_time(probe_ssl_earliest_cert_expiry[10m]) - time()) / 86400, 0.1) < 0'
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: Blackbox SSL certificate expired
            description: "SSL certificate has expired already (instance {{ $labels.instance }})\n"
            dashboard: https://grafana.nsl.xyz/d/NEzutrbMk?var-instance={{ $labels.instance }}&var-job={{ $labels.job }}

        - alert: BlackboxProbeSlowHttp
          expr: 'avg_over_time(probe_http_duration_seconds[1m]) > 2'
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: Blackbox probe slow HTTP
            description: "HTTP request took more than 2s from {{ $labels.job }} (instance {{ $labels.instance }})\n"
            dashboard: https://grafana.nsl.xyz/d/NEzutrbMk?var-instance={{ $labels.instance }}&var-job={{ $labels.job }}

        - alert: BlackboxProbeSlowPing
          expr: 'avg_over_time(probe_icmp_duration_seconds[1m]) > 2'
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: Blackbox probe slow ping
            description: "Blackbox ping took more than 2s from {{ $labels.job }} (instance {{ $labels.instance }})\n"
            dashboard: https://grafana.nsl.xyz/d/NEzutrbMk?var-instance={{ $labels.instance }}&var-job={{ $labels.job }}