apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - additional-scrape-configs.yaml
  - svc.yaml
  - route.yaml

helmCharts:
  - name: victoria-metrics-k8s-stack
    releaseName: victoriametrics
    repo: https://victoriametrics.github.io/helm-charts/
    valuesFile: values.yaml
    version: 0.x.x
    includeCRDs: true
  - name: prometheus-operator-crds
    releaseName: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: x.x.x