apiVersion: apps/v1
kind: Deployment
metadata:
  name: novu-api
  labels:
    app.kubernetes.io/name: novu
    helm.sh/chart: novu-0.1.6
    app.kubernetes.io/instance: novu
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: novu-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: novu
      app.kubernetes.io/instance: novu
      app.kubernetes.io/component: novu-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: novu
        helm.sh/chart: novu-0.1.6
        app.kubernetes.io/instance: novu
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: novu-api
    spec:
      serviceAccountName: novu
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: novu
                    app.kubernetes.io/instance: novu
                    app.kubernetes.io/component: novu-api
                topologyKey: kubernetes.io/hostname
              weight: 1

      containers:
        - name: novu-api
          image: ghcr.io/novuhq/novu/api:0.15.0
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: "production"
            - name: API_ROOT_URL
              value : "https://api.novu.naturalselectionlabs.com"
            - name: DISABLE_USER_REGISTRATION
              value : "false"
            - name: PORT
              value : "3000"
            - name: FRONT_BASE_URL
              value : "https://novu.naturalselectionlabs.com"
            - name: MONGO_MIN_POOL_SIZE
              value : "10"
            - name: MONGO_MAX_POOL_SIZE
              value : "50"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: novu-externalredis
                  key: redis-host
            - name: REDIS_PORT
              value : "6379"
            - name: REDIS_DB_INDEX
              value : "2"
            - name: REDIS_CACHE_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: novu-externalredis
                  key: redis-host
            - name: REDIS_CACHE_SERVICE_PORT
              value : "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: novu-externalredis
                  key: redis-password
            - name: REDIS_CACHE_PASSWORD
              valueFrom :
                secretKeyRef:
                  name: novu-externalredis
                  key: redis-password
            - name: MONGO_URL
              valueFrom :
                secretKeyRef:
                  name: novu-url-mongodb
                  key: mongoUrl
            - name: S3_BUCKET_NAME
              valueFrom :
                secretKeyRef:
                  name: novu-externals3
                  key: bucketName
            - name: S3_REGION
              valueFrom :
                secretKeyRef:
                  name: novu-externals3
                  key: region
            - name: AWS_ACCESS_KEY_ID
              valueFrom :
                secretKeyRef:
                  name: novu-externals3
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom :
                secretKeyRef:
                  name: novu-externals3
                  key: secretKey
            - name: JWT_SECRET
              valueFrom :
                secretKeyRef:
                  name: novu
                  key: jwt-secret
            - name: STORE_ENCRYPTION_KEY
              valueFrom :
                secretKeyRef:
                  name: novu
                  key: store-encryption-key
          resources:
            limits: {}
            requests: {}
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: /v1/health-check
              port: http
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: /v1/health-check
              port: http