name: Run apply.sh

on:
  push:
    branches:
      - 'main'

env:
  AWS_REGION: us-west-2

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm repo add coredns https://coredns.github.io/helm
          helm repo add traefik https://helm.traefik.io/traefik
          helm repo add traefik-mesh https://helm.traefik.io/mesh
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
          helm repo update
      - run: bash ./apply.sh
