name: Run apply

on:
  push:
    branches:
      - 'main'

env:
  REGION_ID: us-east-1
  DEV_ACK_CLUSTER_ID: cd1d0ffc40b5242b39ddda1864e71e30d
  PROD_ACK_CLUSTER_ID: cfc647c22fd6848b5a602ad4d7470632b
  NS: guardian
  CLUSTER: prod
  RUN: no

jobs:
  argo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: set-cluster
        run: |
          if [ ${{ env.CLUSTER }} == 'prod' ]; then
            echo "::set-output name=cluster_id::${{ env.PROD_ACK_CLUSTER_ID }}"
          else
            echo "::set-output name=cluster_id::${{ env.DEV_ACK_CLUSTER_ID }}"
          fi
      - name: Set K8s context
        uses: aliyun/ack-set-context@v1
        with:
          access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
          access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
          cluster-id: "${{ steps.set-cluster.outputs.cluster_id }}"
      - uses: actions-hub/kubectl@master
        with:
          args: apply -k .
