apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []

helmCharts:
  - name: keda
    releaseName: keda
    namespace: guardian
    repo: https://kedacore.github.io/charts
    version: x.x.x
    includeCRDs: true