apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - runner-deploy.yaml
  - network

helmCharts:
  - name: actions-runner-controller
    releaseName: actions-runner-controller
    repo: https://actions-runner-controller.github.io/actions-runner-controller
    valuesFile: values.yaml
    version: 0.x.x
    includeCRDs: true
    namespace: guardian