apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: nsl-runner
  namespace: guardian
spec:
  replicas: 2
  template:
    spec:
      dockerdWithinRunnerContainer: true
      group: Prod
      image: summerwind/actions-runner-dind
      organization: Naturalselectionlabs
      resources:
        requests:
          cpu: '4'
          memory: 8Gi
