nodeSelector:
  rss3.io/usage: internal
tolerations:
  - key: "rss3.io/usage"
    operator: "Equal"
    value: "internal"
    effect: "NoSchedule"
runner:
  statusUpdateHook:
    enabled: true
authSecret:
  name: "action-runner-controller-manager"
metrics:
  serviceMonitor:
    enable: true